core/urls.py
from django.urls import path
from .views import (home, 
                    post_list, 

                    delete_post, 

                    create_post, 
                    like_post, 
                    dislike_post,
                    bookmark,
                    distroy_bookmark,
                    dislike_post, 
                    post_detail,
                    post_instance,
                    post_detail_like,
                    post_detail_dislike,
                    post_detail_distroy_bookmark,
                    post_detail_bookmark,
                    fav_list,
                    create_comment,
                    delete_comment,
                    comment_list
                    )


urlpatterns = [
    path('', home, name="home"),
    path('post_list/', post_list, name="post_list"),
    path('<slug:username>/status/<int:id>/', post_detail, name="post_detail"),
    path('post/<slug:username>/status/<int:id>/', post_instance, name="post_instance"),
    path('<slug:username>/status/<int:id>/detail_like_post', post_detail_like, name="post_detail_like"),
    path('<slug:username>/status/<int:id>/detail_dislike_post', post_detail_dislike, name="post_detail_dislike"),
    path('<slug:username>/bookmarks/', fav_list, name="bookmarks"),

    path('posts/create/', create_post, name="create_post"),
    path('posts/<slug:username>/<int:id>/delete/', delete_post, name="delete_post"),

    #post like, dislike
    path('posts/<slug:username>/<int:id>/like/', like_post, name="like_post"),
    path('posts/<slug:username>/<int:id>/dislike/', dislike_post, name="dislike_post"),

    path('posts/<slug:username>/<int:id>/bookmark/', bookmark, name="bookmark"),
    path('posts/<slug:username>/<int:id>/distroy_bookmark/', distroy_bookmark, name="distroy_bookmark"),
    path('posts/<slug:username>/<int:id>/detail_add_bookmark/', post_detail_bookmark, name="post_detail_bookmark"),
    path('posts/<slug:username>/<int:id>/detail_distroy_bookmark/', post_detail_distroy_bookmark, name="post_detail_distroy_bookmark"),
    #post like, dislike

    #comment
    path('posts/<slug:username>/<int:id>/comment_list/', comment_list, name="comment_list"),
    path('posts/<slug:username>/<int:id>/comment/create/', create_comment, name="create_comment"),
    path('posts/<slug:username>/<int:id>/comment_list/<int:pk>/delete_comment/', delete_comment, name="delete_comment"),

]

django_htmx/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.db.models.fields import TextField
from django.urls import reverse
# Create your models here.

class Post(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    bookmark = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='bookmark', blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.content



class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images", blank=True, null=True)


    def __str__(self):
        return self.post.content



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.content

socialauth/templates/bookmarks.html
{% extends 'base1.html' %}
{% load humanize %}
{% block content %}


<!-- Component Start -->
<div class="flex justify-start bg-white dark:bg-darker w-screen h-screen text-gray-700">
	<div class="flex w-full max-w-screen-lg">
		<div class="flex flex-col flex-grow border-l border-r border-gray-300">
			<div class="flex items-center justify-between flex-shrink-0 px-4 py-2 border-b border-gray-300">
				<h1 class="text-xl font-semibold dark:text-light">
          <svg class="w-6 h-6 inline-block" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M5 4a2 2 0 012-2h6a2 2 0 012 2v14l-5-2.5L5 18V4z"></path></svg>
          Bookmarks
        </h1>
				<a href="#ex1" rel="modal:open" class="hidden md:block lg:block dark:text-light border px-4 py-2">
					<svg class="w-6 h-6 inline-block" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
					New post
				</a>
			</div>
			<div class="flex-grow h-0 overflow-auto">
        
        {% for post in bookmarks %}
        <div class="flex w-full p-8 border-b border-gray-300">
          <img class="flex-shrink-0 w-12 h-12 bg-gray-400 rounded-full" src="{{ post.author.socialaccount_set.all.0.get_avatar_url }}" alt="">
            <div class="flex flex-col flex-grow ml-4">
              <div class="flex dark:text-light">
                <span class="font-semibold">{{ post.author }}</span>
                <span class="ml-1">@{{ post.author }}</span>
              </div>
              <a hx-boost="true" href="{% url 'post_detail' post.author.username post.id %}"><p class="break-words mt-1 dark:text-light my-2">{{ post.content }}</p>
              {% for image in post.images_set.all %}
              <div class="flex items-center justify-center">
                <img class="font-semibold w-full h-full object-cover rounded-3xl" src="{{ image.image.url }}" alt="{{ post.content }}">
              </div>
              {% empty %}
              {% endfor %}
              </a>
              <p class="text-sm dark:text-light font-thin mt-3 text-gray-400">{{ post.created_on }}</p>
          </div>
        </div>
        {% empty %}
        <p class="text-center mt-20">WOW, Such empty</p>
        {% endfor %}

			</div>
		</div>


		<div class="flex flex-col md:block lg:block hidden flex-shrink-0 w-1/4 py-4 pl-4">
			<input class="flex items-center h-8 px-2 border border-gray-500 rounded-sm" type="search" Placeholder="Search…">
			<div>
				<h3 class="mt-6 font-semibold">Trending</h3>
				<div class="flex w-full py-4 border-b border-gray-300">
					<span class="flex-shrink-0 w-10 h-10 bg-gray-400 rounded-full"></span>
					<div class="flex flex-col flex-grow ml-2">
						<div class="flex text-sm">
							<span class="font-semibold">Username</span>
							<span class="ml-1">@username</span>
						</div>
						<p class="mt-1 text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, et dolore magna aliqua. <a class="underline" href="#">#hashtag</a></p>
					</div>
				</div>
				<div class="flex w-full py-4 border-b border-gray-300">
					<span class="flex-shrink-0 w-10 h-10 bg-gray-400 rounded-full"></span>
					<div class="flex flex-col flex-grow ml-2">
						<div class="flex text-sm">
							<span class="font-semibold">Username</span>
							<span class="ml-1">@username</span>
						</div>
						<p class="mt-1 text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, et dolore magna aliqua. <a class="underline" href="#">#hashtag</a></p>
					</div>
				</div>
				<div class="flex w-full py-4 border-b border-gray-300">
					<span class="flex-shrink-0 w-10 h-10 bg-gray-400 rounded-full"></span>
					<div class="flex flex-col flex-grow ml-2">
						<div class="flex text-sm">
							<span class="font-semibold">Username</span>
							<span class="ml-1">@username</span>
						</div>
						<p class="mt-1 text-sm">Lorem ipsum dolor sit amet, consectetur adipiscing elit, et dolore magna aliqua. <a class="underline" href="#">#hashtag</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Component End  -->

<a href="#ex1" rel="modal:open" class="fixed flex items-center justify-center md:hidden lg:hidden block bg-blue-600 rounded-full bottom-8 right-4 mr-4 mb-4 shadow-lg text-blue-100 hover:bg-blue-600" target="_top">
	<div class="flex items-center justify-center h-16 w-16 rounded-full">
		<svg class="w-7 h-7" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
	</div>
</a>


<div id="ex1" class="modal">
  {% include 'create_post.html' %}
</div>




{% endblock content %}

<!--<div class="flex flex-wrap -mx-1 overflow-y-scroll">

    <div class="my-1 px-1 w-full overflow-hidden sm:w-full lg:w-1/2 xl:w-1/2">
      <section class="text-gray-600 body-font mx-2 my-4">
        <div class="container mx-auto">

            <div id="posts">
                {% for post in bookmarks %}
                <div class="px-5 my-1 py-4 bg-white hover:bg-gray-100 cursor-pointer dark:bg-gray-800 shadow rounded-lg max-w-lg">
                <div class="flex mb-4">
                    <a href=""><img class="w-12 h-12 rounded-full" src="{{ post.author.socialaccount_set.all.0.get_avatar_url }}"/></a>
                    <div class="ml-2 mt-0.5">
                    <a href=""><span class="block font-medium text-base leading-snug text-black dark:text-gray-100">u/{{ post.author }}</span></a>
                    <span class="block text-sm text-gray-500 dark:text-gray-400 font-light leading-snug">{{ post.created_on }}</span>
                    </div>
                </div>
                <a hx-boost="true" href="{% url 'post_detail' post.author.username post.id %}"><p class="text-gray-800 dark:text-gray-100 break-all leading-snug md:leading-normal">{{ post.content }}</p></a>
                <div class="flex justify-between items-center mt-5">
                <div class="flex items-center"> 

                </div>  

                </div>
                </div>
                {% empty %}
                <p class="text-center mt-20 font-bold">
                    __Yumpty__
                </p>
                {% endfor %}
            </div>
        </div>
      </section>
    </div>
  
    <div class="my-1 px-1 w-1/2 overflow-hidden sm:w-full lg:w-1/2 xl:w-1/2">
      
    </div>
  
</div>-->    

socialauth/templates/create_comment.html
{% load widget_tweaks %}

<p class="py-2">
  Replying to <span class="font-bold">{{ post.author }}'s</span> post.
</p>
<form
      hx-post="{% url 'create_comment' post.author.username post.id %}"
      hx-target="body" 
      >
    {% csrf_token %}
    {% render_field form.content class="w-full h-28 rounded-lg shadow-md border-gray-200 font-medium" placeholder="write here" %}
    <div class="mx-auto my-1">
      <button class="bg-gray-300 px-2 py-2 rounded-xl" type="submit">
        <svg class="w-6 h-6  transform rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"></path></svg>
      </button>
    </div>
</form>


    

socialauth/templates/post_instance.html
{% load humanize %}

<div id="post_instance">
  <div class="flex w-full p-8 border-b border-gray-300">
    <img
      class="flex-shrink-0 w-12 h-12 bg-gray-400 rounded-full"
      src="{{ post.author.socialaccount_set.all.0.get_avatar_url }}"
      alt=""
    />
    <div class="flex flex-col flex-grow ml-4">
      <div class="flex dark:text-light">
        <span class="font-semibold">{{ post.author }}</span>
        <span class="ml-1">@{{ post.author }}</span>
      </div>
      <p class="break-words mt-1 dark:text-light my-2">{{ post.content }}</p>

      <div class="flex items-center justify-center">
        {% for image in post.images_set.all %}
        <a
          @click="$dispatch('img-modal', {  imgModalSrc: '{{ image.image.url }}', imgModalDesc: '{{ image.post.content }}' })"
        >
          <img
            class="
              transition
              duration-150
              ease-in
              transform
              hover:-translate-y-1 hover:scale-110
              font-semibold
              w-full
              h-48
              object-cover
              rounded-lg
              px-1
              cursor-pointer
            "
            src="{{ image.image.url }}"
            alt="{{ post.content }}"
            data-lightbox="image-1"
            data-title="My caption"
          />
        </a>
        {% empty %} 
        {% endfor %}
      </div>

      <p class="text-sm dark:text-light font-thin mt-3 text-gray-400">
        {{ post.created_on }}
      </p>

      <div class="flex items-center justify-start dark:text-light mt-2">
        <a
          href="#comment_form" rel="modal:open"
          class="text-md mx-1"
        >
          <svg
            class="
              w-7
              h-7
              inline-block
              ml-2
              px-1
              my-1
              rounded-full
              hover:bg-green-100 hover:text-green-500
            "
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
            ></path>
          </svg>
          {{ post.comment_set.count }}
        </a>

        <div>
          {% if request.user.is_authenticated %} 
          {% if request.user in post.likes.all %}
          <button
            class="block hover:text-gray-600 dislike fade-me-out mx-1"
            hx-post="{% url 'post_detail_dislike' post.author.username post.id %}"
            hx-target="#post_instance"
            hx-swap="outerHTML"
          >
            <svg
              class="
                w-7
                h-7
                inline-block
                mx-1
                px-1
                my-1
                cursor-pointer
                rounded-full
                bg-red-100
                text-red-500
              "
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill-rule="evenodd"
                d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                clip-rule="evenodd"
              ></path>
            </svg>
          </button>
          {% else %}
          <button
            class="block hover:text-gray-600 like fade-me-out mx-1"
            hx-post="{% url 'post_detail_like' post.author.username post.id %}"
            hx-target="#post_instance"
            hx-swap="outerHTML"
          >
            <svg
              class="
                w-7
                h-7
                inline-block
                mx-1
                px-1
                my-1
                cursor-pointer
                rounded-full
                hover:bg-red-100 hover:text-red-500
              "
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
              ></path>
            </svg>
          </button>
          {% endif %} 
          {% else %}
          <a
            href="#like"
            rel="modal:open"
            class="block hover:text-gray-600 like fade-me-out"
          >
            <svg
              class="
                w-7
                h-7
                inline-block
                ml-2
                mx-1
                px-1
                my-1
                cursor-pointer
                rounded-full
                hover:bg-red-100 hover:text-red-500
              "
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
              ></path>
            </svg>
          </a>
          {% endif %}
        </div>

        <a class="text-md"> {{ post.likes.count }} </a>

        {% if request.user.is_authenticated %} 
        {% if request.user in post.bookmark.all %}
        <button
          class="block hover:text-gray-600 rem_bookmark fade-me-out"
          hx-post="{% url 'post_detail_distroy_bookmark' post.author.username post.id %}"
          hx-target="#post_instance"
          hx-swap="outerHTML"
        >
          <svg
            class="
              w-7
              h-7
              inline-block
              ml-2
              mx-1
              px-1
              my-1
              cursor-pointer
              rounded-full
              bg-indigo-100
              text-indigo-500
            "
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M5 4a2 2 0 012-2h6a2 2 0 012 2v14l-5-2.5L5 18V4z"></path>
          </svg>
        </button>
        {% else %}
        <button
          class="block hover:text-gray-600 bookmarked fade-me-out"
          hx-post="{% url 'post_detail_bookmark' post.author.username post.id %}"
          hx-target="#post_instance"
          hx-swap="outerHTML"
        >
          <svg
            class="
              w-7
              h-7
              inline-block
              ml-2
              mx-1
              px-1
              my-1
              cursor-pointer
              rounded-full
              hover:bg-indigo-100 hover:text-indigo-500
            "
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"
            ></path>
          </svg>
        </button>
        {% endif %} 
        {% else %}
        <a
          href="#bookmark"
          rel="modal:open"
          class="block hover:text-gray-600 bookmarked fade-me-out"
        >
          <svg
            class="
              w-7
              h-7
              inline-block
              ml-2
              mx-1
              px-1
              my-1
              cursor-pointer
              rounded-full
              hover:bg-indigo-100 hover:text-indigo-500
            "
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"
            ></path>
          </svg>
        </a>
        {% endif %}

        <a class="text-md"> {{ post.bookmark.count }} </a>
      </div>
    </div>
  </div>
</div>

socialauth/templates/post_list.html
{% load humanize %}

<div id="posts">
  {% for post in posts %}
  <div class="flex w-full p-6 border-b border-gray-300">
    <img class="flex-shrink-0 w-12 h-12 bg-gray-400 rounded-full"
      src="{{ post.author.socialaccount_set.all.0.get_avatar_url }}" alt="" />
    <div class="flex flex-col flex-grow ml-4">
      <div class="flex">
        <span class="font-semibold dark:text-light">{{ post.author }}</span>
        <span class="ml-1 opacity-100 dark:text-gray-200 text-gray-400">u/{{ post.author }}</span>
        <span class="ml-auto">
          {% if post.author == request.user %}
          <a class="block text-red-600 dark:text-red-600 fade-me-out"
            hx-delete="{% url 'delete_post' post.author.username post.id %}" hx-target="#posts" hx-swap="outerHTML">
            <svg class="
                w-6
                h-6
                inline-block
                ml-2
                px-1
                my-1
                cursor-pointer
                rounded-full
                hover:bg-red-100
              " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16">
              </path>
            </svg>
          </a>
          {% endif %}
        </span>
      </div>
      <a hx-boost="true" href="{% url 'post_detail' post.author.username post.id  %}">
        <p class="break-words mt-1 dark:text-light my-2">
          {{ post.content }}
        </p>
      </a>

      <div class="flex items-center justify-start">
        {% for image in post.images_set.all %}
        <a
          @click="$dispatch('img-modal', {  imgModalSrc: '{{ image.image.url }}', imgModalDesc: '{{ image.post.content }}' })">
          <img class="
              transition
              duration-150
              ease-in
              transform
              hover:-translate-y-1 hover:scale-110
              font-semibold
              w-full
              h-48
              object-cover
              rounded-lg
              px-1
              cursor-pointer
            " src="{{ image.image.url }}" alt="{{ post.content }}" data-lightbox="image-1" data-title="My caption" />
        </a>
        {% empty %}
        {% endfor %}
      </div>

      <p class="text-sm dark:text-light font-thin mt-3 text-gray-400">
        {{ post.created_on }}
      </p>


      <div class="flex items-center justify-start dark:text-light mt-2">
        <a hx-boost="true" href="{% url 'post_detail' post.author.username post.id %}" class="text-md mx-1">
          <svg class="
              w-7
              h-7
              inline-block
              ml-2
              px-1
              my-1
              rounded-full
              hover:bg-green-100 hover:text-green-500
            " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z">
            </path>
          </svg>
          {{ post.comment_set.count }}
        </a>

        <div>
          {% if request.user.is_authenticated %}
          {% if request.user in post.likes.all %}
          <button class="block hover:text-gray-600 dislike fade-me-out mx-1"
            hx-post="{% url 'dislike_post' post.author.username post.id %}" hx-target="#posts" hx-swap="outerHTML">
            <svg class="
                w-7
                h-7
                inline-block
                mx-1
                px-1
                my-1
                cursor-pointer
                rounded-full
                bg-red-100
                text-red-500
              " fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                clip-rule="evenodd"></path>
            </svg>
          </button>
          {% else %}
          <button class="block hover:text-gray-600 like fade-me-out mx-1"
            hx-post="{% url 'like_post' post.author.username post.id %}" hx-target="#posts" hx-swap="outerHTML">
            <svg class="
                w-7
                h-7
                inline-block
                mx-1
                px-1
                my-1
                cursor-pointer
                rounded-full
                hover:bg-red-100 hover:text-red-500
              " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
              </path>
            </svg>
          </button>
          {% endif %}
          {% else %}
          <a href="#like" rel="modal:open" class="block hover:text-gray-600 like fade-me-out">
            <svg class="
                w-7
                h-7
                inline-block
                ml-2
                mx-1
                px-1
                my-1
                cursor-pointer
                rounded-full
                hover:bg-red-100 hover:text-red-500
              " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
              </path>
            </svg>
          </a>
          {% endif %}
        </div>

        <a class="text-md"> {{ post.likes.count }} </a>

        {% if request.user.is_authenticated %}
        {% if request.user in post.bookmark.all %}
        <button class="block hover:text-gray-600 rem_bookmark fade-me-out"
          hx-post="{% url 'distroy_bookmark' post.author.username post.id %}" hx-target="#posts" hx-swap="outerHTML">
          <svg class="
              w-7
              h-7
              inline-block
              ml-2
              mx-1
              px-1
              my-1
              cursor-pointer
              rounded-full
              bg-indigo-100
              text-indigo-500
            " fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path d="M5 4a2 2 0 012-2h6a2 2 0 012 2v14l-5-2.5L5 18V4z"></path>
          </svg>
        </button>
        {% else %}
        <button class="block hover:text-gray-600 bookmarked fade-me-out"
          hx-post="{% url 'bookmark' post.author.username post.id %}" hx-target="#posts" hx-swap="outerHTML">
          <svg class="
              w-7
              h-7
              inline-block
              ml-2
              mx-1
              px-1
              my-1
              cursor-pointer
              rounded-full
              hover:bg-indigo-100 hover:text-indigo-500
            " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"></path>
          </svg>
        </button>
        {% endif %}
        {% else %}
        <a href="#bookmark" rel="modal:open" class="block hover:text-gray-600 bookmarked fade-me-out">
          <svg class="
              w-7
              h-7
              inline-block
              ml-2
              mx-1
              px-1
              my-1
              cursor-pointer
              rounded-full
              hover:bg-indigo-100 hover:text-indigo-500
            " fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"></path>
          </svg>
        </a>
        {% endif %}

        <a class="text-md"> {{ post.bookmark.count }} </a>
      </div>


    </div>
  </div>
  {% empty %}
  <p class="text-center my-20">Wow, such empty</p>
  {% endfor %}
</div>